### ISSUE TITLE
Allow supervisors to remove specific students from queue

### ISSUE THREAD

**Issue by snctfd** [bjornregnell/sigrid#15]
Would be handy if a student leaves the room while there are still others in the queue.

**Comment by bjornregnell** [comment]
Good idea! The form for supervisors could e.g. include a text field with comma-separated user names that gets deleted - but this is somewhat risky if people are not nice so maybe we need to introduce authentication for supervisors (see issue #14) as well.

**Comment by bjornregnell** [comment]
This is probably a wont-fix if we want to keep authentication-less login.

**Comment by bjornregnell** [comment]
How important is this? Is it really worth it to introduce authentication for beppe?

**Comment by bjornregnell** [comment]
I'm closing this as won't fix for now.
