### ISSUE TITLE
Room closed in the middle of lab session

### ISSUE THREAD

**Issue by hnrklssn** [bjornregnell/sigrid#19]
It's quite confusing and irritating for everyone involved when a room times out and is removed, while a lab is active and people are queueing for help. I propose we never remove rooms when the following criteria hold:
 - The room is not empty. Could be limited to just making sure the queues aren't empty.
 - It's before 18 on a week day

**Comment by bjornregnell** [comment]
There is a check that the room is not active, see here: 
https://github.com/bjornregnell/sigrid/blob/master/src/main/scala/model.scala#L94
