### ISSUE TITLE
Add awareness of scheduled rooms

### ISSUE THREAD

**Issue by theolundqvist** [bjornregnell/sigrid#26]
Virtual rooms with similar names could all be pointing to the same physical room. Mostly this occurs when students fail to spell the room name correctly.

By requesting data from kaptenalloc or the google sheet "pgk-dod-allokering-utfall" Sigrid could be made to automatically open the relevant rooms. By doing this we could also create a fancy UI with "join" buttons for each open room.

**Comment by theolundqvist** [comment]
An approach for requesting data from the spreadsheet is presented in #27

**Comment by bjornregnell** [comment]
I have added a warning for unknown room now. Hopefully that will help avoiding students being in the wrong room... The downside with requiring rooms to be in the schedule is that you cannot use a fake room if the real one has been hacked...

**Comment by bjornregnell** [comment]
related to #32
