### ISSUE TITLE
Reset Sigrid rooms on 2 hour intervals

### ISSUE THREAD

**Issue by oliverlevay** [bjornregnell/sigrid#29]
It is a common problem where people are stuck in the queues in empty rooms which causes confusion for ambulances.

**Comment by bjornregnell** [comment]
We better to fix this by allowing many supervisors in each room so ambulance can log in and purge an old room. What do you think?

**Comment by bjornregnell** [comment]
I'm closing this now, as fixed intervals will reduce applicability if people want do use sigrid outside schedule slots...
