### ISSUE TITLE
Varg is not considered a known room.

### ISSUE THREAD

**Issue by pontussjostedt** [bjornregnell/sigrid#31]

**Comment by bjornregnell** [comment]
Thanks. Val and Falk is also missing... Fixed now here: https://github.com/bjornregnell/sigrid/commit/cce447c13eb35a3aa5bbbc0018592fbc47ac82e4

But I'll wait to update Sigrid live until during lunch-time...

**Comment by bjornregnell** [comment]
now live on offical url. @pontussjostedt Does Sigrid work now as expected?

**Comment by pontussjostedt** [comment]
Verkar fungera!!!
